package org.ops4j.gaderian.parse;

/**
 * @author Johan Lindquist
 */
public enum DescriptorParsingState
{
    STATE_START, STATE_MODULE, STATE_CONFIGURATION_POINT, STATE_CONTRIBUTION, STATE_SERVICE_POINT,
    STATE_CREATE_INSTANCE, STATE_IMPLEMENTATION, STATE_SCHEMA, STATE_ELEMENT, STATE_RULES,
    STATE_COLLECT_SERVICE_PARAMETERS, STATE_CONVERSION, STATE_LWDOM, STATE_NO_CONTENT
}
